apiVersion: apps/v1
kind: Deployment
metadata:
    name: room-services
spec:
    selector:
        matchLabels:
            app: room-services
            tier: backend
            track: stable
    replicas: 1
    template:
        metadata:
            labels:
                app: room-services
                tier: backend
                track: stable
        spec:
            container:
                - name: room-services
                  image: pedrocastillo/room-services
                  ports:
                    - name: http
                    containerPort: 8001